package com.tanguyantoine.react;

import androidx.annotation.NonNull;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;

/**
 * Abstract spec class for MusicControl TurboModule
 * This class will be auto-generated by Codegen in a real implementation
 * For now, we provide a base implementation to enable development
 */
public abstract class NativeMusicControlSpec extends ReactContextBaseJavaModule implements TurboModule {

    public NativeMusicControlSpec(ReactApplicationContext context) {
        super(context);
    }

    @ReactMethod
    public abstract void enableBackgroundMode(boolean enable);

    @ReactMethod
    public abstract void setNowPlaying(@NonNull ReadableMap info);

    @ReactMethod
    public abstract void updatePlayback(@NonNull ReadableMap info);

    @ReactMethod
    public abstract void resetNowPlaying();

    @ReactMethod
    public abstract void stopControl();

    @ReactMethod
    public abstract void enableControl(@NonNull String controlName, boolean enable, @NonNull ReadableMap options);

    @ReactMethod
    public abstract void setNotificationIds(double notificationId, @NonNull String channelId);

    @ReactMethod
    public abstract void observeAudioInterruptions(boolean enable);

    @ReactMethod
    public abstract void addListener(String eventName);

    @ReactMethod
    public abstract void removeListeners(double count);
}
