#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
#import <ReactCommon/RCTTurboModule.h>
#import <MediaPlayer/MediaPlayer.h>

// Forward declaration of the generated spec
@protocol NativeMusicControlSpec;

/**
 * TurboModule interface for MusicControlManager
 * Supports both New Architecture (TurboModule) and Legacy Architecture
 */
@interface MusicControlManager : RCTEventEmitter <RCTBridgeModule, RCTTurboModule>

@end

/**
 * Protocol definition that matches the TypeScript spec
 * This will be auto-generated by Codegen in the final implementation
 */
@protocol NativeMusicControlSpec <NSObject>

- (void)enableBackgroundMode:(BOOL)enable;
- (void)setNowPlaying:(NSDictionary *)info;
- (void)updatePlayback:(NSDictionary *)info;
- (void)resetNowPlaying;
- (void)stopControl;
- (void)enableControl:(NSString *)controlName enable:(BOOL)enable options:(NSDictionary *)options;
- (void)observeAudioInterruptions:(BOOL)enable;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;

@end
