name: Publish Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: write
      packages: write 
    steps:
      - uses: vimtor/action-update-version@v1
        with:
          files: './package.json'
          repo-token: ${{ secrets.GITHUB_TOKEN }}   

      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          
      - run: cd swagger/client && npm ci  
      - run: cd swagger/client && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}